global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']

  - job_name: 'docker-exporter'
    static_configs:
      - targets: ['docker-exporter:9487']

  - job_name: 'io-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['io-service:8080']

  - job_name: 'cpu-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cpu-service:8081']

  - job_name: 'load-generator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['load-generator:8082']
